-- Puzzles generated by the server (SERVER_PUZZLES). The seed stays on the server, and the
-- competitive time of a ranked solve is measured from issued_at.
CREATE TABLE tickets (
	id TEXT PRIMARY KEY,
	player_id TEXT NOT NULL REFERENCES players (id),
	game TEXT NOT NULL,
	variant TEXT NOT NULL,
	puzzle_id INTEGER NOT NULL,
	puzzle TEXT NOT NULL,
	issued_at INTEGER NOT NULL,
	solved_at INTEGER
);

CREATE INDEX tickets_player ON tickets (player_id, issued_at);
